apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: stephengrider/multi-worker
          ports:
              - containerPort: 3000
# To update the kubernete pod use this command
# kubectl apply -f <filename>

# Get detailed info about an object. <object name> is optional.
# kubectl describe <object type> <object name>

# kubectl delete -f <config file>
