apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: eduardogoncalves551/multi-client-03-01
                  ports:
                      - containerPort: 3000
# kubectl apply -f k8s ==> Apply all the files inside the folder k8s
