apiVersion: v1
kind: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    # See the selector in postgres-deployment.yaml to know the name of the component
    selector:
        component: postgres
    ports:
        # port to the outside
        - port: 5432
          targetPort: 5432
