apiVersion: v1
kind: Service
metadata:
    # clusterIP service name, it's kind of an URL
    name: redis-cluster-ip-service
spec:
    type: ClusterIP
    # See the selector in redis-deployment.yaml to know the name of the component
    selector:
        component: redis
    ports:
        # port to the outside
        - port: 6379
          targetPort: 6379
