apiVersion: v1
kind: Service
metadata:
    name: server-cluster-ip-service
spec:
    type: ClusterIP
    # See the selector in server-deployment.yaml to know the name of the component
    selector:
        component: server
    ports:
        # port to the outside
        - port: 5000
          targetPort: 5000
